//HintName: Spangle.Tests.GeneratedButEmptyWithNoAmf0FieldTestStruct.g.cs
// <auto-generated/>
#nullable enable
#pragma warning disable CS8600
#pragma warning disable CS8601
#pragma warning disable CS8602
#pragma warning disable CS8603
#pragma warning disable CS8604

using System.IO.Pipelines;
using Spangle.Rtmp.Amf0;

namespace Spangle.Tests;

internal partial struct GeneratedButEmptyWithNoAmf0FieldTestStruct
{
    /// <summary>
    /// Write this structure itself to the buffer.
    /// </summary>
    public int ToAmf0Object(PipeWriter writer)
    {
        int total = 0;

        total += Amf0Writer.WriteObjectHeader(writer);
        total += Amf0Writer.WriteObjectEnd(writer);

        writer.Advance(total);
        return total;
    }
}
