//HintName: Spangle.Tests.GeneratedButEmptyWithNoAmf0FieldTestStruct.g.cs
// <auto-generated/>
#nullable enable
#pragma warning disable CS8600
#pragma warning disable CS8601
#pragma warning disable CS8602
#pragma warning disable CS8603
#pragma warning disable CS8604

using System.Buffers;
using Spangle.Transport.Rtmp.Amf0;

namespace Spangle.Tests;

internal partial struct GeneratedButEmptyWithNoAmf0FieldTestStruct : IAmf0Serializable
{
    /// <summary>
    /// Serialize this struct as an AMF0 byte sequence.
    /// </summary>
    public int WriteBytes(IBufferWriter<byte> writer)
    {
        var total = 0;
        return total;
    }
}
